name: 'Continuous Integration'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: accuracode/workflow-continuous-integration/.github/workflows/testing.yml@main

  code-ql:
    needs: [ test ]
    uses: accuracode/workflow-continuous-integration/.github/workflows/code-quality.yml@main

  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
